fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.1.0'
    wget:
      repo: 'maestrodev/wget'
      ref: '1.5.1'
    ant:
      repo: 'maestrodev/ant'
      ref: '1.0.5'
    archive:
      repo: 'gini/archive'
      ref: '0.2.0'
  symlinks:
    thrift: "#{source_dir}"
